// src/constants/localization.ts
import { Platform, NativeModules } from 'react-native';
import { I18n } from 'i18n-js';

export const TRANSLATION_KEYS = {
  hello_again: 'hello_again',
  email: 'email',
  password: 'password',
  forgot_password: 'forgot_password',
  login: 'login',
  dont_have_account: 'dont_have_account',
  registration: 'registration',
  welcome: 'welcome',
  enter_email: 'enter_email',
  next: 'next',
  register_with_phone: 'register_with_phone',
  create_password: 'create_password',
  must_contain: 'must_contain',
  new_password: 'new_password',
  confirm_password: 'confirm_password',
  choose_username: 'choose_username',
  username_info: 'username_info',
  username: 'username',
  finish: 'finish',
  otp_instruction: 'otp_instruction',
  resend_code: 'resend_code',
  tab_post: 'tab_post',
  tab_location: 'tab_location',
  tab_profile: 'tab_profile',
  tab_menu: 'tab_menu',
  profile_rate_app: 'profile_rate_app',
  profile_help: 'profile_help',
  profile_terms: 'profile_terms',
  profile_privacy: 'profile_privacy',
  profile_logout: 'profile_logout',
  profile_delete_account: 'profile_delete_account',
  profile_user_since: 'profile_user_since',
  profile_personal_info: 'profile_personal_info',
  profile_vehicle: 'profile_vehicle',
  profile_verify: 'profile_verify',
  profile_opinions: 'profile_opinions',
  profile_payments_management: 'profile_payments_management',
  profile_close_session: 'profile_close_session',
  menu_passenger: 'menu_passenger',
  menu_driver: 'menu_driver',
  menu_filter: 'menu_filter',
  menu_scheduled: 'menu_scheduled',
  menu_finished: 'menu_finished',
  menu_cancelled: 'menu_cancelled',
  post_not_driver: 'post_not_driver',
  post_driver_instruction: 'post_driver_instruction',
  post_become_driver: 'post_become_driver',
  steps_message: 'steps_message',
  add_vehicle_step1_title: 'add_vehicle_step1_title',
  add_vehicle_step1_subtitle: 'add_vehicle_step1_subtitle',
  vehicle_brand: 'vehicle_brand',
  select_brand: 'select_brand',
  vehicle_model: 'vehicle_model',
  select_model: 'select_model',
  vehicle_color: 'vehicle_color',
  enter_color: 'enter_color',
  vehicle_plate: 'vehicle_plate',
  enter_plate: 'enter_plate',
  vehicle_tag: 'vehicle_tag',
  select_tag: 'select_tag',
  add_vehicle_later: 'add_vehicle_later',
  vehicle_register_confirm_question: 'vehicle_register_confirm_question',
  vehicle_register_confirm_info: 'vehicle_register_confirm_info',
  Confirm: 'Confirm',
  name: 'name',
  last_name: 'last_name',
  birth_date: 'birth_date',
  phone_number: 'phone_number',
  additional_info: 'additional_info',
  keep: 'keep',
  verify_driver: 'verify_driver',
  upload_driver_both_side_license: 'upload_driver_both_side_license',
  front_side:'front_side',
  back_side:'back_side',
  send:'send',  
  verify_email: 'verify_email',
  enter_email_send_to_mail: 'enter_email_send_to_mail',
  
};

const translations = {
  en: {
    [TRANSLATION_KEYS.hello_again]: 'Hello again!',
    [TRANSLATION_KEYS.email]: 'Email',
    [TRANSLATION_KEYS.password]: 'Password',
    [TRANSLATION_KEYS.forgot_password]: 'Forgot your password?',
    [TRANSLATION_KEYS.login]: 'Login',
    [TRANSLATION_KEYS.dont_have_account]: "Don't have an account?",
    [TRANSLATION_KEYS.registration]: 'Registration',
    [TRANSLATION_KEYS.welcome]: 'Welcome!',
    [TRANSLATION_KEYS.enter_email]: 'Enter your email address to start the registration process.',
    [TRANSLATION_KEYS.next]: 'Next',
    [TRANSLATION_KEYS.register_with_phone]: 'Register with phone number',
    [TRANSLATION_KEYS.create_password]: 'Create a password that we have sent by Email',
    [TRANSLATION_KEYS.must_contain]: 'Must contain at least 6 alphanumeric characters',
    [TRANSLATION_KEYS.new_password]: 'New Password',
    [TRANSLATION_KEYS.confirm_password]: 'Confirm Password',
    [TRANSLATION_KEYS.choose_username]: 'Choose a username',
    [TRANSLATION_KEYS.username_info]: 'This is the name other users will see you by.',
    [TRANSLATION_KEYS.username]: 'User name',
    [TRANSLATION_KEYS.finish]: 'Finish',
    [TRANSLATION_KEYS.otp_instruction]: 'Please enter the 5-digit code we sent via Email.',
    [TRANSLATION_KEYS.resend_code]: 'Resend Code',
    [TRANSLATION_KEYS.tab_post]: 'Post',
    [TRANSLATION_KEYS.tab_location]: 'Location',
    [TRANSLATION_KEYS.tab_profile]: 'Profile',
    [TRANSLATION_KEYS.tab_menu]: 'Menu',
    [TRANSLATION_KEYS.profile_rate_app]: 'Rate the App',
    [TRANSLATION_KEYS.profile_help]: 'Help',
    [TRANSLATION_KEYS.profile_terms]: 'Terms and Conditions',
    [TRANSLATION_KEYS.profile_privacy]: 'Privacy Policy',
    [TRANSLATION_KEYS.profile_logout]: 'Log out',
    [TRANSLATION_KEYS.profile_delete_account]: 'Delete account',
    [TRANSLATION_KEYS.profile_user_since]: 'User since {{date}}',
    [TRANSLATION_KEYS.profile_personal_info]: 'Personal Info',
    [TRANSLATION_KEYS.profile_vehicle]: 'Vehicle',
    [TRANSLATION_KEYS.profile_verify]: 'Verify',
    [TRANSLATION_KEYS.profile_opinions]: 'Opinions',
    [TRANSLATION_KEYS.profile_payments_management]: 'Payments management',
    [TRANSLATION_KEYS.profile_close_session]: 'Close session',
    [TRANSLATION_KEYS.menu_passenger]: 'Passenger',
    [TRANSLATION_KEYS.menu_driver]: 'Driver',
    [TRANSLATION_KEYS.menu_filter]: 'Filter',
    [TRANSLATION_KEYS.menu_scheduled]: 'Scheduled',
    [TRANSLATION_KEYS.menu_finished]: 'Finished',
    [TRANSLATION_KEYS.menu_cancelled]: 'Cancelled',
    [TRANSLATION_KEYS.post_not_driver]: "Wow... you're not a driver yet",
    [TRANSLATION_KEYS.post_driver_instruction]: "To be able to publish trips, you must first register as a driver",
    [TRANSLATION_KEYS.post_become_driver]: "I want to be a driver",
    [TRANSLATION_KEYS.steps_message]: "Only 2 steps (5 minutes)",
    [TRANSLATION_KEYS.add_vehicle_step1_title]: 'Step 1: Add a vehicle',
    [TRANSLATION_KEYS.add_vehicle_step1_subtitle]: 'Register the vehicle you will use to carry passengers',
    [TRANSLATION_KEYS.vehicle_brand]: 'Vehicle brand',
    [TRANSLATION_KEYS.select_brand]: 'Select brand',
    [TRANSLATION_KEYS.vehicle_model]: 'Vehicle model',
    [TRANSLATION_KEYS.select_model]: 'Select model',
    [TRANSLATION_KEYS.vehicle_color]: 'Vehicle color',
    [TRANSLATION_KEYS.enter_color]: 'Enter color',
    [TRANSLATION_KEYS.vehicle_plate]: 'Vehicle plate',
    [TRANSLATION_KEYS.enter_plate]: '0000XXX',
    [TRANSLATION_KEYS.vehicle_tag]: 'Vehicle tag',
    [TRANSLATION_KEYS.select_tag]: 'Select tag',
    [TRANSLATION_KEYS.add_vehicle_later]: 'Leave for later',
    [TRANSLATION_KEYS.vehicle_register_confirm_question]: 'Are you sure you want to register this vehicle?',
    [TRANSLATION_KEYS.vehicle_register_confirm_info]: 'Remember you can always edit this information or register new vehicles from your Profile',
    [TRANSLATION_KEYS.Confirm]: 'Confirm',
    [TRANSLATION_KEYS.name]: 'Name',
    [TRANSLATION_KEYS.last_name]: 'Last Name',
    [TRANSLATION_KEYS.birth_date]: 'Birth Date',
    [TRANSLATION_KEYS.phone_number]: 'Phone Number',
    [TRANSLATION_KEYS.additional_info]: 'Additional Information',
    [TRANSLATION_KEYS.keep]: 'Keep',
    [TRANSLATION_KEYS.verify_driver]: 'Verify Driver',
    [TRANSLATION_KEYS.upload_driver_both_side_license]: "Upload a photo of your driver's license on both sides",
    [TRANSLATION_KEYS.front_side]: 'Front Side',
    [TRANSLATION_KEYS.back_side]: 'Back Side',
    [TRANSLATION_KEYS.send]: 'Send',
    [TRANSLATION_KEYS.verify_email]: 'Verify Email',
    [TRANSLATION_KEYS.enter_email_send_to_mail]: "Enter your email and we'll send you a verification email.",
  },
  es: {
    [TRANSLATION_KEYS.hello_again]: '¡Hola de nuevo!',
    [TRANSLATION_KEYS.email]: 'Correo electrónico',
    [TRANSLATION_KEYS.password]: 'Contraseña',
    [TRANSLATION_KEYS.forgot_password]: '¿Has olvidado tu contraseña?',
    [TRANSLATION_KEYS.login]: 'Iniciar sesión',
    [TRANSLATION_KEYS.dont_have_account]: '¿No tienes una cuenta?',
    [TRANSLATION_KEYS.registration]: 'Regístrate',
    [TRANSLATION_KEYS.welcome]: '¡Bienvenido!',
    [TRANSLATION_KEYS.enter_email]: 'Introduce tu correo electrónico para comenzar el registro.',
    [TRANSLATION_KEYS.next]: 'Siguiente',
    [TRANSLATION_KEYS.register_with_phone]: 'Registrarse con número de teléfono',
    [TRANSLATION_KEYS.create_password]: 'Crea una contraseña que te hemos enviado por Email',
    [TRANSLATION_KEYS.must_contain]: 'Debe contener al menos 6 caracteres alfanuméricos',
    [TRANSLATION_KEYS.new_password]: 'Nueva contraseña',
    [TRANSLATION_KEYS.confirm_password]: 'Confirmar contraseña',
    [TRANSLATION_KEYS.choose_username]: 'Elige un nombre de usuario',
    [TRANSLATION_KEYS.username_info]: 'Este es el nombre que verán otros usuarios.',
    [TRANSLATION_KEYS.username]: 'Nombre de usuario',
    [TRANSLATION_KEYS.finish]: 'Finalizar',
    [TRANSLATION_KEYS.otp_instruction]: 'Por favor, introduce el código de 5 dígitos que enviamos por Email.',
    [TRANSLATION_KEYS.resend_code]: 'Reenviar código',
    [TRANSLATION_KEYS.tab_post]: 'Publicar',
    [TRANSLATION_KEYS.tab_location]: 'Buscar',
    [TRANSLATION_KEYS.tab_profile]: 'Perfil',
    [TRANSLATION_KEYS.tab_menu]: 'Mis viajes',
    [TRANSLATION_KEYS.profile_rate_app]: 'Valora la App',
    [TRANSLATION_KEYS.profile_help]: 'Ayuda',
    [TRANSLATION_KEYS.profile_terms]: 'Términos y condiciones',
    [TRANSLATION_KEYS.profile_privacy]: 'Política de privacidad',
    [TRANSLATION_KEYS.profile_logout]: 'Cerrar sesión',
    [TRANSLATION_KEYS.profile_delete_account]: 'Eliminar cuenta',
    [TRANSLATION_KEYS.profile_user_since]: 'Usuario desde {{date}}',
    [TRANSLATION_KEYS.profile_personal_info]: 'Información personal',
    [TRANSLATION_KEYS.profile_vehicle]: 'Vehículo',
    [TRANSLATION_KEYS.profile_verify]: 'Verificar',
    [TRANSLATION_KEYS.profile_opinions]: 'Opiniones',
    [TRANSLATION_KEYS.profile_payments_management]: 'Gestión de pagos',
    [TRANSLATION_KEYS.profile_close_session]: 'Cerrar sesión',
    [TRANSLATION_KEYS.menu_passenger]: 'Pasajero',
    [TRANSLATION_KEYS.menu_driver]: 'Conductor',
    [TRANSLATION_KEYS.menu_filter]: 'Filtro',
    [TRANSLATION_KEYS.menu_scheduled]: 'Programados',
    [TRANSLATION_KEYS.menu_finished]: 'Finalizadas',
    [TRANSLATION_KEYS.menu_cancelled]: 'Cancelados',
    [TRANSLATION_KEYS.post_not_driver]: 'Vaya... todavía no eres conductor',
    [TRANSLATION_KEYS.post_driver_instruction]: 'Para poder publicar viajes, primero debes registrarte como conductor',
    [TRANSLATION_KEYS.post_become_driver]: 'Quiero ser conductor',
    [TRANSLATION_KEYS.steps_message]: 'Solo son 2 pasos (5 minutos)',
    [TRANSLATION_KEYS.add_vehicle_step1_title]: 'Paso 1: Añade un vehículo',
    [TRANSLATION_KEYS.add_vehicle_step1_subtitle]: 'Registra el vehículo que utilizarás para llevar pasajeros',
    [TRANSLATION_KEYS.vehicle_brand]: 'Marca del vehículo',
    [TRANSLATION_KEYS.select_brand]: 'Selecciona la marca',
    [TRANSLATION_KEYS.vehicle_model]: 'Modelo del vehículo',
    [TRANSLATION_KEYS.select_model]: 'Selecciona el modelo',
    [TRANSLATION_KEYS.vehicle_color]: 'Color del vehículo',
    [TRANSLATION_KEYS.enter_color]: 'Escribe el color',
    [TRANSLATION_KEYS.vehicle_plate]: 'Matrícula del vehículo',
    [TRANSLATION_KEYS.enter_plate]: '0000XXX',
    [TRANSLATION_KEYS.vehicle_tag]: 'Etiqueta del vehículo',
    [TRANSLATION_KEYS.select_tag]: 'Selecciona la etiqueta',
    [TRANSLATION_KEYS.add_vehicle_later]: 'Dejar para más tarde',
    [TRANSLATION_KEYS.vehicle_register_confirm_question]: '¿Estás seguro de que quieres registrar este vehículo?',
    [TRANSLATION_KEYS.vehicle_register_confirm_info]: 'Recuerda que siempre puedes editar esta información o registrar nuevos vehículos desde tu Perfil.',
    [TRANSLATION_KEYS.Confirm]: 'Confirmar',
    [TRANSLATION_KEYS.name]: 'Nombre',
    [TRANSLATION_KEYS.last_name]: 'Apellido',
    [TRANSLATION_KEYS.birth_date]: 'Fecha de nacimiento',
    [TRANSLATION_KEYS.phone_number]: 'Número de teléfono',
    [TRANSLATION_KEYS.additional_info]: 'Información adicional',
    [TRANSLATION_KEYS.keep]: 'Guardar',
    [TRANSLATION_KEYS.verify_driver]: 'Verificar conductor',
    [TRANSLATION_KEYS.upload_driver_both_side_license]: 'Sube una foto de tu permiso de conducir por ambas caras',
    [TRANSLATION_KEYS.front_side]: 'Cara delantera',
    [TRANSLATION_KEYS.back_side]: 'Cara trasera',
    [TRANSLATION_KEYS.send]: 'Enviar',
    [TRANSLATION_KEYS.verify_email]: 'Verificar email',
    [TRANSLATION_KEYS.enter_email_send_to_mail]: 'Introduce tu correo electrónico y te enviaremos un correo de verificación.',
    
  },
};

const getDeviceLocale = () => {
  let locale = 'en';
//   if (Platform.OS === 'ios') {
//     locale = NativeModules.SettingsManager?.settings?.AppleLocale ||
//       NativeModules.SettingsManager?.settings?.AppleLanguages?.[0] || 'en';
//   } else if (Platform.OS === 'android') {
//     locale = NativeModules.I18nManager?.localeIdentifier || 'en';
//   }
  return locale.replace('_', '-').split('-')[0];
};

const i18n = new I18n(translations);
i18n.locale = getDeviceLocale();
i18n.enableFallback = true;

export default i18n;
